###################################################################

# Created by write_sdc on Sat Jan  9 01:22:53 2021

###################################################################
set sdc_version 1.8

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max slow -max_library slow\
                         -min fast -min_library fast
set_wire_load_model -name tsmc13_wl10 -library slow
set_load -pin_load 1 [get_ports mem_wen_D]
set_load -pin_load 1 [get_ports {mem_addr_D[31]}]
set_load -pin_load 1 [get_ports {mem_addr_D[30]}]
set_load -pin_load 1 [get_ports {mem_addr_D[29]}]
set_load -pin_load 1 [get_ports {mem_addr_D[28]}]
set_load -pin_load 1 [get_ports {mem_addr_D[27]}]
set_load -pin_load 1 [get_ports {mem_addr_D[26]}]
set_load -pin_load 1 [get_ports {mem_addr_D[25]}]
set_load -pin_load 1 [get_ports {mem_addr_D[24]}]
set_load -pin_load 1 [get_ports {mem_addr_D[23]}]
set_load -pin_load 1 [get_ports {mem_addr_D[22]}]
set_load -pin_load 1 [get_ports {mem_addr_D[21]}]
set_load -pin_load 1 [get_ports {mem_addr_D[20]}]
set_load -pin_load 1 [get_ports {mem_addr_D[19]}]
set_load -pin_load 1 [get_ports {mem_addr_D[18]}]
set_load -pin_load 1 [get_ports {mem_addr_D[17]}]
set_load -pin_load 1 [get_ports {mem_addr_D[16]}]
set_load -pin_load 1 [get_ports {mem_addr_D[15]}]
set_load -pin_load 1 [get_ports {mem_addr_D[14]}]
set_load -pin_load 1 [get_ports {mem_addr_D[13]}]
set_load -pin_load 1 [get_ports {mem_addr_D[12]}]
set_load -pin_load 1 [get_ports {mem_addr_D[11]}]
set_load -pin_load 1 [get_ports {mem_addr_D[10]}]
set_load -pin_load 1 [get_ports {mem_addr_D[9]}]
set_load -pin_load 1 [get_ports {mem_addr_D[8]}]
set_load -pin_load 1 [get_ports {mem_addr_D[7]}]
set_load -pin_load 1 [get_ports {mem_addr_D[6]}]
set_load -pin_load 1 [get_ports {mem_addr_D[5]}]
set_load -pin_load 1 [get_ports {mem_addr_D[4]}]
set_load -pin_load 1 [get_ports {mem_addr_D[3]}]
set_load -pin_load 1 [get_ports {mem_addr_D[2]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[63]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[62]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[61]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[60]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[59]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[58]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[57]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[56]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[55]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[54]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[53]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[52]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[51]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[50]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[49]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[48]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[47]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[46]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[45]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[44]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[43]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[42]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[41]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[40]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[39]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[38]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[37]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[36]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[35]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[34]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[33]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[32]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[31]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[30]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[29]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[28]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[27]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[26]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[25]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[24]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[23]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[22]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[21]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[20]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[19]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[18]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[17]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[16]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[15]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[14]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[13]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[12]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[11]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[10]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[9]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[8]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[7]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[6]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[5]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[4]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[3]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[2]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[1]}]
set_load -pin_load 1 [get_ports {mem_wdata_D[0]}]
set_load -pin_load 1 [get_ports {mem_addr_I[31]}]
set_load -pin_load 1 [get_ports {mem_addr_I[30]}]
set_load -pin_load 1 [get_ports {mem_addr_I[29]}]
set_load -pin_load 1 [get_ports {mem_addr_I[28]}]
set_load -pin_load 1 [get_ports {mem_addr_I[27]}]
set_load -pin_load 1 [get_ports {mem_addr_I[26]}]
set_load -pin_load 1 [get_ports {mem_addr_I[25]}]
set_load -pin_load 1 [get_ports {mem_addr_I[24]}]
set_load -pin_load 1 [get_ports {mem_addr_I[23]}]
set_load -pin_load 1 [get_ports {mem_addr_I[22]}]
set_load -pin_load 1 [get_ports {mem_addr_I[21]}]
set_load -pin_load 1 [get_ports {mem_addr_I[20]}]
set_load -pin_load 1 [get_ports {mem_addr_I[19]}]
set_load -pin_load 1 [get_ports {mem_addr_I[18]}]
set_load -pin_load 1 [get_ports {mem_addr_I[17]}]
set_load -pin_load 1 [get_ports {mem_addr_I[16]}]
set_load -pin_load 1 [get_ports {mem_addr_I[15]}]
set_load -pin_load 1 [get_ports {mem_addr_I[14]}]
set_load -pin_load 1 [get_ports {mem_addr_I[13]}]
set_load -pin_load 1 [get_ports {mem_addr_I[12]}]
set_load -pin_load 1 [get_ports {mem_addr_I[11]}]
set_load -pin_load 1 [get_ports {mem_addr_I[10]}]
set_load -pin_load 1 [get_ports {mem_addr_I[9]}]
set_load -pin_load 1 [get_ports {mem_addr_I[8]}]
set_load -pin_load 1 [get_ports {mem_addr_I[7]}]
set_load -pin_load 1 [get_ports {mem_addr_I[6]}]
set_load -pin_load 1 [get_ports {mem_addr_I[5]}]
set_load -pin_load 1 [get_ports {mem_addr_I[4]}]
set_load -pin_load 1 [get_ports {mem_addr_I[3]}]
set_load -pin_load 1 [get_ports {mem_addr_I[2]}]
set_max_fanout 6 [get_ports clk]
set_max_fanout 6 [get_ports rst_n]
set_max_fanout 6 [get_ports {mem_rdata_D[63]}]
set_max_fanout 6 [get_ports {mem_rdata_D[62]}]
set_max_fanout 6 [get_ports {mem_rdata_D[61]}]
set_max_fanout 6 [get_ports {mem_rdata_D[60]}]
set_max_fanout 6 [get_ports {mem_rdata_D[59]}]
set_max_fanout 6 [get_ports {mem_rdata_D[58]}]
set_max_fanout 6 [get_ports {mem_rdata_D[57]}]
set_max_fanout 6 [get_ports {mem_rdata_D[56]}]
set_max_fanout 6 [get_ports {mem_rdata_D[55]}]
set_max_fanout 6 [get_ports {mem_rdata_D[54]}]
set_max_fanout 6 [get_ports {mem_rdata_D[53]}]
set_max_fanout 6 [get_ports {mem_rdata_D[52]}]
set_max_fanout 6 [get_ports {mem_rdata_D[51]}]
set_max_fanout 6 [get_ports {mem_rdata_D[50]}]
set_max_fanout 6 [get_ports {mem_rdata_D[49]}]
set_max_fanout 6 [get_ports {mem_rdata_D[48]}]
set_max_fanout 6 [get_ports {mem_rdata_D[47]}]
set_max_fanout 6 [get_ports {mem_rdata_D[46]}]
set_max_fanout 6 [get_ports {mem_rdata_D[45]}]
set_max_fanout 6 [get_ports {mem_rdata_D[44]}]
set_max_fanout 6 [get_ports {mem_rdata_D[43]}]
set_max_fanout 6 [get_ports {mem_rdata_D[42]}]
set_max_fanout 6 [get_ports {mem_rdata_D[41]}]
set_max_fanout 6 [get_ports {mem_rdata_D[40]}]
set_max_fanout 6 [get_ports {mem_rdata_D[39]}]
set_max_fanout 6 [get_ports {mem_rdata_D[38]}]
set_max_fanout 6 [get_ports {mem_rdata_D[37]}]
set_max_fanout 6 [get_ports {mem_rdata_D[36]}]
set_max_fanout 6 [get_ports {mem_rdata_D[35]}]
set_max_fanout 6 [get_ports {mem_rdata_D[34]}]
set_max_fanout 6 [get_ports {mem_rdata_D[33]}]
set_max_fanout 6 [get_ports {mem_rdata_D[32]}]
set_max_fanout 6 [get_ports {mem_rdata_D[31]}]
set_max_fanout 6 [get_ports {mem_rdata_D[30]}]
set_max_fanout 6 [get_ports {mem_rdata_D[29]}]
set_max_fanout 6 [get_ports {mem_rdata_D[28]}]
set_max_fanout 6 [get_ports {mem_rdata_D[27]}]
set_max_fanout 6 [get_ports {mem_rdata_D[26]}]
set_max_fanout 6 [get_ports {mem_rdata_D[25]}]
set_max_fanout 6 [get_ports {mem_rdata_D[24]}]
set_max_fanout 6 [get_ports {mem_rdata_D[23]}]
set_max_fanout 6 [get_ports {mem_rdata_D[22]}]
set_max_fanout 6 [get_ports {mem_rdata_D[21]}]
set_max_fanout 6 [get_ports {mem_rdata_D[20]}]
set_max_fanout 6 [get_ports {mem_rdata_D[19]}]
set_max_fanout 6 [get_ports {mem_rdata_D[18]}]
set_max_fanout 6 [get_ports {mem_rdata_D[17]}]
set_max_fanout 6 [get_ports {mem_rdata_D[16]}]
set_max_fanout 6 [get_ports {mem_rdata_D[15]}]
set_max_fanout 6 [get_ports {mem_rdata_D[14]}]
set_max_fanout 6 [get_ports {mem_rdata_D[13]}]
set_max_fanout 6 [get_ports {mem_rdata_D[12]}]
set_max_fanout 6 [get_ports {mem_rdata_D[11]}]
set_max_fanout 6 [get_ports {mem_rdata_D[10]}]
set_max_fanout 6 [get_ports {mem_rdata_D[9]}]
set_max_fanout 6 [get_ports {mem_rdata_D[8]}]
set_max_fanout 6 [get_ports {mem_rdata_D[7]}]
set_max_fanout 6 [get_ports {mem_rdata_D[6]}]
set_max_fanout 6 [get_ports {mem_rdata_D[5]}]
set_max_fanout 6 [get_ports {mem_rdata_D[4]}]
set_max_fanout 6 [get_ports {mem_rdata_D[3]}]
set_max_fanout 6 [get_ports {mem_rdata_D[2]}]
set_max_fanout 6 [get_ports {mem_rdata_D[1]}]
set_max_fanout 6 [get_ports {mem_rdata_D[0]}]
set_max_fanout 6 [get_ports {mem_rdata_I[31]}]
set_max_fanout 6 [get_ports {mem_rdata_I[30]}]
set_max_fanout 6 [get_ports {mem_rdata_I[29]}]
set_max_fanout 6 [get_ports {mem_rdata_I[28]}]
set_max_fanout 6 [get_ports {mem_rdata_I[27]}]
set_max_fanout 6 [get_ports {mem_rdata_I[26]}]
set_max_fanout 6 [get_ports {mem_rdata_I[25]}]
set_max_fanout 6 [get_ports {mem_rdata_I[24]}]
set_max_fanout 6 [get_ports {mem_rdata_I[23]}]
set_max_fanout 6 [get_ports {mem_rdata_I[22]}]
set_max_fanout 6 [get_ports {mem_rdata_I[21]}]
set_max_fanout 6 [get_ports {mem_rdata_I[20]}]
set_max_fanout 6 [get_ports {mem_rdata_I[19]}]
set_max_fanout 6 [get_ports {mem_rdata_I[18]}]
set_max_fanout 6 [get_ports {mem_rdata_I[17]}]
set_max_fanout 6 [get_ports {mem_rdata_I[16]}]
set_max_fanout 6 [get_ports {mem_rdata_I[15]}]
set_max_fanout 6 [get_ports {mem_rdata_I[14]}]
set_max_fanout 6 [get_ports {mem_rdata_I[13]}]
set_max_fanout 6 [get_ports {mem_rdata_I[12]}]
set_max_fanout 6 [get_ports {mem_rdata_I[11]}]
set_max_fanout 6 [get_ports {mem_rdata_I[10]}]
set_max_fanout 6 [get_ports {mem_rdata_I[9]}]
set_max_fanout 6 [get_ports {mem_rdata_I[8]}]
set_max_fanout 6 [get_ports {mem_rdata_I[7]}]
set_max_fanout 6 [get_ports {mem_rdata_I[6]}]
set_max_fanout 6 [get_ports {mem_rdata_I[5]}]
set_max_fanout 6 [get_ports {mem_rdata_I[4]}]
set_max_fanout 6 [get_ports {mem_rdata_I[3]}]
set_max_fanout 6 [get_ports {mem_rdata_I[2]}]
set_max_fanout 6 [get_ports {mem_rdata_I[1]}]
set_max_fanout 6 [get_ports {mem_rdata_I[0]}]
set_ideal_network [get_ports clk]
create_clock [get_ports clk]  -name CLK  -period 6.5  -waveform {0 3.25}
set_clock_latency 0.5  [get_clocks CLK]
set_clock_uncertainty 0.1  [get_clocks CLK]
set_input_delay -clock CLK  0.1  [get_ports rst_n]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[63]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[62]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[61]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[60]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[59]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[58]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[57]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[56]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[55]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[54]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[53]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[52]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[51]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[50]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[49]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[48]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[47]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[46]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[45]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[44]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[43]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[42]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[41]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[40]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[39]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[38]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[37]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[36]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[35]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[34]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[33]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[32]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[31]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[30]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[29]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[28]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[27]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[26]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[25]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[24]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[23]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[22]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[21]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[20]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[19]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[18]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[17]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[16]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[15]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[14]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[13]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[12]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[11]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[10]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[9]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[8]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[7]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[6]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[5]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[4]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[3]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[2]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[1]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_D[0]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[31]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[30]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[29]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[28]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[27]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[26]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[25]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[24]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[23]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[22]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[21]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[20]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[19]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[18]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[17]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[16]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[15]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[14]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[13]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[12]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[11]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[10]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[9]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[8]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[7]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[6]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[5]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[4]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[3]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[2]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[1]}]
set_input_delay -clock CLK  0.1  [get_ports {mem_rdata_I[0]}]
set_output_delay -clock CLK  0.1  [get_ports mem_wen_D]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[31]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[30]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[29]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[28]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[27]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[26]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[25]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[24]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[23]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[22]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[21]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[20]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[19]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[18]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[17]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[16]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[15]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[14]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[13]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[12]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[11]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[10]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[9]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[8]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[7]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[6]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[5]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[4]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[3]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_D[2]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[63]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[62]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[61]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[60]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[59]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[58]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[57]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[56]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[55]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[54]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[53]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[52]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[51]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[50]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[49]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[48]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[47]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[46]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[45]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[44]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[43]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[42]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[41]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[40]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[39]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[38]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[37]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[36]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[35]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[34]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[33]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[32]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[31]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[30]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[29]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[28]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[27]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[26]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[25]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[24]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[23]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[22]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[21]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[20]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[19]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[18]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[17]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[16]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[15]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[14]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[13]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[12]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[11]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[10]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[9]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[8]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[7]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[6]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[5]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[4]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[3]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[2]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[1]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_wdata_D[0]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[31]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[30]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[29]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[28]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[27]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[26]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[25]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[24]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[23]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[22]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[21]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[20]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[19]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[18]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[17]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[16]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[15]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[14]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[13]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[12]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[11]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[10]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[9]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[8]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[7]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[6]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[5]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[4]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[3]}]
set_output_delay -clock CLK  0.1  [get_ports {mem_addr_I[2]}]
set_drive 1  [get_ports clk]
set_drive 1  [get_ports rst_n]
set_drive 1  [get_ports {mem_rdata_D[63]}]
set_drive 1  [get_ports {mem_rdata_D[62]}]
set_drive 1  [get_ports {mem_rdata_D[61]}]
set_drive 1  [get_ports {mem_rdata_D[60]}]
set_drive 1  [get_ports {mem_rdata_D[59]}]
set_drive 1  [get_ports {mem_rdata_D[58]}]
set_drive 1  [get_ports {mem_rdata_D[57]}]
set_drive 1  [get_ports {mem_rdata_D[56]}]
set_drive 1  [get_ports {mem_rdata_D[55]}]
set_drive 1  [get_ports {mem_rdata_D[54]}]
set_drive 1  [get_ports {mem_rdata_D[53]}]
set_drive 1  [get_ports {mem_rdata_D[52]}]
set_drive 1  [get_ports {mem_rdata_D[51]}]
set_drive 1  [get_ports {mem_rdata_D[50]}]
set_drive 1  [get_ports {mem_rdata_D[49]}]
set_drive 1  [get_ports {mem_rdata_D[48]}]
set_drive 1  [get_ports {mem_rdata_D[47]}]
set_drive 1  [get_ports {mem_rdata_D[46]}]
set_drive 1  [get_ports {mem_rdata_D[45]}]
set_drive 1  [get_ports {mem_rdata_D[44]}]
set_drive 1  [get_ports {mem_rdata_D[43]}]
set_drive 1  [get_ports {mem_rdata_D[42]}]
set_drive 1  [get_ports {mem_rdata_D[41]}]
set_drive 1  [get_ports {mem_rdata_D[40]}]
set_drive 1  [get_ports {mem_rdata_D[39]}]
set_drive 1  [get_ports {mem_rdata_D[38]}]
set_drive 1  [get_ports {mem_rdata_D[37]}]
set_drive 1  [get_ports {mem_rdata_D[36]}]
set_drive 1  [get_ports {mem_rdata_D[35]}]
set_drive 1  [get_ports {mem_rdata_D[34]}]
set_drive 1  [get_ports {mem_rdata_D[33]}]
set_drive 1  [get_ports {mem_rdata_D[32]}]
set_drive 1  [get_ports {mem_rdata_D[31]}]
set_drive 1  [get_ports {mem_rdata_D[30]}]
set_drive 1  [get_ports {mem_rdata_D[29]}]
set_drive 1  [get_ports {mem_rdata_D[28]}]
set_drive 1  [get_ports {mem_rdata_D[27]}]
set_drive 1  [get_ports {mem_rdata_D[26]}]
set_drive 1  [get_ports {mem_rdata_D[25]}]
set_drive 1  [get_ports {mem_rdata_D[24]}]
set_drive 1  [get_ports {mem_rdata_D[23]}]
set_drive 1  [get_ports {mem_rdata_D[22]}]
set_drive 1  [get_ports {mem_rdata_D[21]}]
set_drive 1  [get_ports {mem_rdata_D[20]}]
set_drive 1  [get_ports {mem_rdata_D[19]}]
set_drive 1  [get_ports {mem_rdata_D[18]}]
set_drive 1  [get_ports {mem_rdata_D[17]}]
set_drive 1  [get_ports {mem_rdata_D[16]}]
set_drive 1  [get_ports {mem_rdata_D[15]}]
set_drive 1  [get_ports {mem_rdata_D[14]}]
set_drive 1  [get_ports {mem_rdata_D[13]}]
set_drive 1  [get_ports {mem_rdata_D[12]}]
set_drive 1  [get_ports {mem_rdata_D[11]}]
set_drive 1  [get_ports {mem_rdata_D[10]}]
set_drive 1  [get_ports {mem_rdata_D[9]}]
set_drive 1  [get_ports {mem_rdata_D[8]}]
set_drive 1  [get_ports {mem_rdata_D[7]}]
set_drive 1  [get_ports {mem_rdata_D[6]}]
set_drive 1  [get_ports {mem_rdata_D[5]}]
set_drive 1  [get_ports {mem_rdata_D[4]}]
set_drive 1  [get_ports {mem_rdata_D[3]}]
set_drive 1  [get_ports {mem_rdata_D[2]}]
set_drive 1  [get_ports {mem_rdata_D[1]}]
set_drive 1  [get_ports {mem_rdata_D[0]}]
set_drive 1  [get_ports {mem_rdata_I[31]}]
set_drive 1  [get_ports {mem_rdata_I[30]}]
set_drive 1  [get_ports {mem_rdata_I[29]}]
set_drive 1  [get_ports {mem_rdata_I[28]}]
set_drive 1  [get_ports {mem_rdata_I[27]}]
set_drive 1  [get_ports {mem_rdata_I[26]}]
set_drive 1  [get_ports {mem_rdata_I[25]}]
set_drive 1  [get_ports {mem_rdata_I[24]}]
set_drive 1  [get_ports {mem_rdata_I[23]}]
set_drive 1  [get_ports {mem_rdata_I[22]}]
set_drive 1  [get_ports {mem_rdata_I[21]}]
set_drive 1  [get_ports {mem_rdata_I[20]}]
set_drive 1  [get_ports {mem_rdata_I[19]}]
set_drive 1  [get_ports {mem_rdata_I[18]}]
set_drive 1  [get_ports {mem_rdata_I[17]}]
set_drive 1  [get_ports {mem_rdata_I[16]}]
set_drive 1  [get_ports {mem_rdata_I[15]}]
set_drive 1  [get_ports {mem_rdata_I[14]}]
set_drive 1  [get_ports {mem_rdata_I[13]}]
set_drive 1  [get_ports {mem_rdata_I[12]}]
set_drive 1  [get_ports {mem_rdata_I[11]}]
set_drive 1  [get_ports {mem_rdata_I[10]}]
set_drive 1  [get_ports {mem_rdata_I[9]}]
set_drive 1  [get_ports {mem_rdata_I[8]}]
set_drive 1  [get_ports {mem_rdata_I[7]}]
set_drive 1  [get_ports {mem_rdata_I[6]}]
set_drive 1  [get_ports {mem_rdata_I[5]}]
set_drive 1  [get_ports {mem_rdata_I[4]}]
set_drive 1  [get_ports {mem_rdata_I[3]}]
set_drive 1  [get_ports {mem_rdata_I[2]}]
set_drive 1  [get_ports {mem_rdata_I[1]}]
set_drive 1  [get_ports {mem_rdata_I[0]}]
